// <auto-generated />
namespace ClothBazar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class OrderAndOrderItemTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderAndOrderItemTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202005092229470_OrderAndOrderItemTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
